name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: duongleeaaa
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Backend image
        uses: docker/build-push-action@v4
        with:
          context: ./todo-list
          file: ./todo-list/Dockerfile
          push: true
          tags: duongleeaaa/todo-list-backend:latest

      - name: Build and push Frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./todo-list-fe
          file: ./todo-list-fe/Dockerfile
          push: true
          tags: duongleeaaa/todo-list-frontend:latest

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 3.26.129.247
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Di chuyển tới thư mục chứa project (có chứa file docker-compose.yml)
            cd ~/HN_KS23B_LeKhanhDuong_009

            # Kéo (pull) image mới nhất về máy chủ
            docker compose pull

            # Khởi động lại các container ở chế độ background
            docker compose up -d
